import { button } from '../functions/html.js';
import { pageHeader } from '../functions/view.js';

export function settings(store) {
  const config = store.state.configuration || { settings: {}, dalas: [] };
  const saved = config.settings || {};
  const mapping = saved.pdf_field_mapping || {};
  const fields = [['codigo', 'Código do produto'], ['data', 'Data do carregamento'], ['expedidor', 'Expedidor'], ['placa', 'Placa do caminhão'], ['motorista', 'Motorista'], ['produto', 'Identificador do produto'], ['quantidade', 'Quantidade']];
  return `${pageHeader('Sistema / configuração','Configurações','Gateway, comunicação Ethernet do CLP e parâmetros de importação PDF.')}<section class="panel"><h3>Rede do cliente</h3><form id="settings-form"><label>IP público ou DDNS do gateway<input name="gateway_public_ip" value="${saved.gateway_public_ip || ''}" placeholder="203.0.113.5" /></label><label>URL da API cloud<input name="sync_remote_url" type="url" value="${saved.sync_remote_url || ''}" placeholder="https://api.exemplo.com" /></label><h3>Mapeamento do PDF</h3>${fields.map(([key, label]) => `<label>${label}<input name="pdf_${key}" value="${mapping[key] || ''}" /></label>`).join('')}${button('Salvar configuração','save-settings')}</form></section><br><section class="panel"><h3>Nova Dala / equipamento</h3><form id="dala-form"><div class="grid two"><label>Identificador<input name="equipment_code" required placeholder="esteira_01" /></label><label>Nome<input name="name" required placeholder="Esteira principal" /></label><label>IP do CLP<input name="plc_ip" required placeholder="192.168.1.10" /></label><label>Porta do CLP<input name="plc_port" type="number" value="502" min="1" max="65535" required /></label><label>Porta externa<input name="external_port" type="number" min="1" max="65535" placeholder="8101" /></label><label>Protocolo<select name="plc_protocol"><option value="MODBUS_TCP">Modbus TCP</option><option value="MODBUS_RTU">Modbus RTU</option></select></label></div>${button('Cadastrar Dala','save-dala')}</form></section><br><section class="panel"><h3>Dalas / equipamentos</h3><p>Configuração de comunicação Ethernet com o CLP. Os endereços ainda podem ser preenchidos após a validação da rede industrial.</p><div class="table-wrap"><table><thead><tr><th>Nome</th><th>Identificador</th><th>IP do CLP</th><th>Porta</th><th>Porta externa</th><th>Protocolo</th></tr></thead><tbody>${config.dalas.length ? config.dalas.map((dala) => `<tr><td>${dala.name}</td><td>${dala.equipment_code}</td><td>${dala.plc_ip || '—'}</td><td>${dala.plc_port || 502}</td><td>${dala.external_port || '—'}</td><td>${dala.plc_protocol || 'MODBUS_TCP'}</td></tr>`).join('') : '<tr><td colspan="6">Nenhum equipamento cadastrado.</td></tr>'}</tbody></table></div></section>`;
}
