server {
    listen 80;
    server_name _;
    root /var/www/frontend;
    index index.html;
    add_header Content-Security-Policy "default-src 'self'; connect-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self'; frame-ancestors 'none'" always;
    add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~ ^/api/(.+\.php)$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/backend/public/$1;
        fastcgi_pass php:9000;
    }

}
