import { el } from './functions/html.js';
import { TraceStore } from './classes/TraceStore.js';
import { TraceRouter } from './classes/TraceRouter.js';
import { home } from './screens/home.js';
import { manifests, importScreen, division, work } from './screens/operations.js';
import { occurrences, summary, history, tablet, products, alerts, emergency } from './screens/monitoring.js';
import { settings } from './screens/settings.js';

const store = new TraceStore();
const screens = { home, manifests, import: importScreen, division, work, occurrences, summary, history, tablet, products, alerts, emergency, settings };
const router = new TraceRouter(store, render);
const groups = [['Operação',[['home','Home'],['manifests','Romaneios do dia'],['import','Importar CSV'],['division','Divisão por caminhão'],['work','Tela de trabalho']]],['Acompanhamento',[['alerts','Alertas'],['occurrences','Ocorrências'],['summary','Resumo final'],['history','Histórico'],['tablet','Monitor tablet']]],['Cadastros',[['products','Produtos'],['emergency','Emergência']]],['Sistema',[['settings','Configurações']]]];
let authenticatedUser = null;

function loginView(message = '') { return `<main class="login-page"><section class="login-card"><div class="brand login-brand"><strong>TRACE</strong><small>PLATFORM CGP</small></div><p class="kicker">Acesso local</p><h1>Dallogix Trace</h1><p class="login-description">Entre para acessar a rastreabilidade de carregamento.</p>${message ? `<div class="login-error">${message}</div>` : ''}<form id="login-form"><label>E-mail<input name="email" type="email" value="admin@dallogix.local" autocomplete="username" required /></label><label>Senha<input name="password" type="password" autocomplete="current-password" required /></label><button class="button primary login-button" type="submit">Entrar no sistema</button></form><small class="login-hint">Ambiente local • sem dependência de internet</small></section></main>`; }
function layout() { return `<div class="shell"><aside class="sidebar"><div class="brand"><strong>TRACE</strong><small>PLATFORM CGP</small></div><nav>${groups.map(([label, items]) => `<span class="nav-label">${label}</span>${items.map(([id, title]) => `<button class="nav-item ${store.state.page === id ? 'active' : ''}" data-action="${id}">${title}</button>`).join('')}`).join('')}</nav><footer>${authenticatedUser.name}<br><b>${authenticatedUser.role}</b><br>Modo local • ESTEIRA_01<br><button class="logout-link" data-action="logout">Sair</button></footer></aside><main class="main"><header class="topbar"><h1>Dallogix Trace <small>/ rastreabilidade de carregamento</small></h1><span class="local">● Sistema local online</span></header><section class="content">${screens[store.state.page](store)}</section></main></div>`; }
function render(message = '') { el('#app').innerHTML = authenticatedUser ? layout() : loginView(message); bindActions(); }
function downloadCsv(filename, rows) { const csv = rows.map((row) => row.map((value) => `"${String(value ?? '').replaceAll('"', '""')}"`).join(';')).join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([`\ufeff${csv}`], { type: 'text/csv;charset=utf-8' })); link.download = filename; link.click(); URL.revokeObjectURL(link.href); }
function bindActions() { document.querySelectorAll('[data-action]').forEach((node) => node.addEventListener('click', async () => { const action = node.dataset.action; if (action === 'logout') { await fetch('/api/logout.php', { method: 'POST', headers: store.csrfToken ? { 'X-CSRF-Token': store.csrfToken } : {} }); authenticatedUser = null; render(); return; } if (screens[action]) router.go(action); else if (action === 'run') { try { await store.changeLoadingState('CARREGANDO'); render(); } catch (error) { alert(error.message); } } else if (action === 'stop') { try { await store.changeLoadingState('PAUSADO'); render(); } catch (error) { alert(error.message); } } else if (action === 'return') { store.toggleReturn(); render(); } else if (action === 'emergency') { try { await store.changeLoadingState('EMERGENCIA'); store.activateEmergency(); render(); } catch (error) { alert(error.message); } } else if (action === 'unlock') { try { await store.unlockMachine(); render(); } catch (error) { alert(error.message); } } else if (action === 'finish') { try { await store.finishLoading(); alert('Carregamento finalizado.'); render(); } catch (error) { alert(error.message); } } else if (action === 'export') { downloadCsv(`dallogix-${store.state.page}.csv`, [['Campo', 'Valor'], ['Romaneio', store.state.romaneio], ['Caminhão', store.state.truck], ['Estado', store.state.operationalState], ['Carregado', store.state.loaded], ['Planejado', store.state.planned], ['Sincronização pendente', store.state.monitoring?.sync_pendente || 0]]); } else if (action === 'new-product') { const code = prompt('Código do produto:'); const name = prompt('Nome do produto:'); const barcode = prompt('Código de barras:'); if (code && name && barcode) { try { await store.createProduct({ code, name, barcode }); render(); } catch (error) { alert(error.message); } } } }));
  const form = document.querySelector('#login-form');
  if (form) form.addEventListener('submit', async (event) => { event.preventDefault(); const data = Object.fromEntries(new FormData(form)); const response = await fetch('/api/login.php', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) }); const result = await response.json(); if (!response.ok) { render(result.error || 'Não foi possível entrar.'); return; } authenticatedUser = result.user; store.setCsrfToken(result.csrf_token); render(); });
  const occurrenceForm = document.querySelector('#occurrence-form');
  if (occurrenceForm) occurrenceForm.addEventListener('submit', async (event) => { event.preventDefault(); try { await store.createOccurrence(Object.fromEntries(new FormData(occurrenceForm))); render(); } catch (error) { alert(error.message); } });
  const settingsForm = document.querySelector('#settings-form');
  if (settingsForm) settingsForm.addEventListener('submit', async (event) => { event.preventDefault(); const raw = Object.fromEntries(new FormData(settingsForm)); const pdf_field_mapping = {}; Object.entries(raw).filter(([key]) => key.startsWith('pdf_')).forEach(([key, value]) => { if (value) pdf_field_mapping[key.slice(4)] = value; }); try { await store.saveConfiguration({ gateway_public_ip: raw.gateway_public_ip, sync_remote_url: raw.sync_remote_url, pdf_field_mapping }); alert('Configuração salva.'); render(); } catch (error) { alert(error.message); } });
  const dalaForm = document.querySelector('#dala-form');
  if (dalaForm) dalaForm.addEventListener('submit', async (event) => { event.preventDefault(); try { await store.createEquipment(Object.fromEntries(new FormData(dalaForm))); alert('Dala cadastrada.'); render(); } catch (error) { alert(error.message); } });
  const csvForm = document.querySelector('#csv-form');
  if (csvForm) csvForm.addEventListener('submit', async (event) => { event.preventDefault(); const response = await fetch('/api/importar_csv.php', { method: 'POST', headers: store.csrfToken ? { 'X-CSRF-Token': store.csrfToken } : {}, body: new FormData(csvForm) }); const result = await response.json(); if (!response.ok) { alert(result.error || 'Falha ao importar CSV.'); return; } await store.loadManifests(); alert(`${result.data.items} item(ns) importado(s).`); router.go('manifests'); });
}
async function bootstrap() { const response = await fetch('/api/me.php'); if (response.ok) { const result = await response.json(); authenticatedUser = result.user; store.setUser(authenticatedUser); store.setCsrfToken(result.csrf_token); await store.loadManifests(); await store.loadActiveLoading(); await store.loadMonitoring(); await store.loadProducts(); await store.loadConfiguration(); } render(); }
bootstrap();
