import { el } from './functions/html.js';
import { TraceStore } from './classes/TraceStore.js';
import { TraceRouter } from './classes/TraceRouter.js';
import { home } from './screens/home.js';
import { manifests, importScreen, division, work } from './screens/operations.js';
import { occurrences, summary, history, tablet, products, alerts, emergency } from './screens/monitoring.js';

const store = new TraceStore();
const screens = { home, manifests, import: importScreen, division, work, occurrences, summary, history, tablet, products, alerts, emergency };
const router = new TraceRouter(store, render);
const groups = [['Operação',[['home','Home'],['manifests','Romaneios do dia'],['import','Importar CSV'],['division','Divisão por caminhão'],['work','Tela de trabalho']]],['Acompanhamento',[['alerts','Alertas'],['occurrences','Ocorrências'],['summary','Resumo final'],['history','Histórico'],['tablet','Monitor tablet']]],['Cadastros',[['products','Produtos'],['emergency','Emergência']]]];
let authenticatedUser = null;

function loginView(message = '') { return `<main class="login-page"><section class="login-card"><div class="brand login-brand"><strong>TRACE</strong><small>PLATFORM CGP</small></div><p class="kicker">Acesso local</p><h1>Dallogix Trace</h1><p class="login-description">Entre para acessar a rastreabilidade de carregamento.</p>${message ? `<div class="login-error">${message}</div>` : ''}<form id="login-form"><label>E-mail<input name="email" type="email" value="admin@dallogix.local" autocomplete="username" required /></label><label>Senha<input name="password" type="password" value="password" autocomplete="current-password" required /></label><button class="button primary login-button" type="submit">Entrar no sistema</button></form><small class="login-hint">Ambiente local • sem dependência de internet</small></section></main>`; }
function layout() { return `<div class="shell"><aside class="sidebar"><div class="brand"><strong>TRACE</strong><small>PLATFORM CGP</small></div><nav>${groups.map(([label, items]) => `<span class="nav-label">${label}</span>${items.map(([id, title]) => `<button class="nav-item ${store.state.page === id ? 'active' : ''}" data-action="${id}">${title}</button>`).join('')}`).join('')}</nav><footer>${authenticatedUser.name}<br><b>${authenticatedUser.role}</b><br>Modo local • ESTEIRA_01<br><button class="logout-link" data-action="logout">Sair</button></footer></aside><main class="main"><header class="topbar"><h1>Dallogix Trace <small>/ rastreabilidade de carregamento</small></h1><span class="local">● Sistema local online</span></header><section class="content">${screens[store.state.page](store)}</section></main></div>`; }
function render(message = '') { el('#app').innerHTML = authenticatedUser ? layout() : loginView(message); bindActions(); }
function bindActions() { document.querySelectorAll('[data-action]').forEach((node) => node.addEventListener('click', async () => { const action = node.dataset.action; if (action === 'logout') { await fetch('/api/logout.php', { method: 'POST' }); authenticatedUser = null; render(); return; } if (screens[action]) router.go(action); else if (action === 'run') { try { await store.changeLoadingState('CARREGANDO'); render(); } catch (error) { alert(error.message); } } else if (action === 'stop') { try { await store.changeLoadingState('PAUSADO'); render(); } catch (error) { alert(error.message); } } else if (action === 'return') { store.toggleReturn(); render(); } else if (action === 'emergency') { try { await store.changeLoadingState('EMERGENCIA'); store.activateEmergency(); render(); } catch (error) { alert(error.message); } } else if (action === 'unlock') { try { await store.unlockMachine(); render(); } catch (error) { alert(error.message); } } else if (['validate','export','saved'].includes(action)) alert('Ação ainda não disponível nesta etapa.'); }));
  const form = document.querySelector('#login-form');
  if (form) form.addEventListener('submit', async (event) => { event.preventDefault(); const data = Object.fromEntries(new FormData(form)); const response = await fetch('/api/login.php', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) }); const result = await response.json(); if (!response.ok) { render(result.error || 'Não foi possível entrar.'); return; } authenticatedUser = result.user; render(); });
  const occurrenceForm = document.querySelector('#occurrence-form');
  if (occurrenceForm) occurrenceForm.addEventListener('submit', async (event) => { event.preventDefault(); try { await store.createOccurrence(Object.fromEntries(new FormData(occurrenceForm))); render(); } catch (error) { alert(error.message); } });
  const csvForm = document.querySelector('#csv-form');
  if (csvForm) csvForm.addEventListener('submit', async (event) => { event.preventDefault(); const response = await fetch('/api/importar_csv.php', { method: 'POST', body: new FormData(csvForm) }); const result = await response.json(); if (!response.ok) { alert(result.error || 'Falha ao importar CSV.'); return; } await store.loadManifests(); alert(`${result.data.items} item(ns) importado(s).`); router.go('manifests'); });
}
async function bootstrap() { const response = await fetch('/api/me.php'); if (response.ok) { const result = await response.json(); authenticatedUser = result.user; store.setUser(authenticatedUser); await store.loadManifests(); await store.loadActiveLoading(); await store.loadMonitoring(); await store.loadProducts(); } render(); }
bootstrap();
